server:
  port: 8082
spring:
  application:
    name: cart-service
  cloud:
    nacos:
      server-addr: 192.168.11.135:8848
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true #请求路径
  rabbitmq:
    host: 192.168.11.135 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    connection-timeout: 1s
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
  #    template:
#      retry:
#        enabled: true # 开启超时重试机制
#        initial-interval: 1000ms # 失败后的初始等待时间
#        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
#        max-attempts: 3 # 最大重试次数
#    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
#    publisher-returns: true # 开启publisher return机制
  profiles:
    active: dev

hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123